### ISSUE TITLE
[BUG] KeyError: 'slots'

### ISSUE THREAD

**Issue by rgaufman** [ButterflyBug/Tesco_delivery_checker#14]
When I run the script, it says:

```
$ TESCO_EMAIL="my email" TESCO_PASSWORD="my password" python bin/run_checker.py
Traceback (most recent call last):
  File "bin/run_checker.py", line 11, in <module>
    check()
  File "/Users/hackeron/Development/Tesco_delivery_checker/tesco_delivery_checker/check.py", line 155, in check
    for period_result in period_results:
  File "/Users/hackeron/Development/Tesco_delivery_checker/tesco_delivery_checker/check.py", line 152, in <lambda>
    period_results = map(lambda url: get_slots_for_date(url, session), periods_urls)
  File "/Users/hackeron/Development/Tesco_delivery_checker/tesco_delivery_checker/check.py", line 48, in get_slots_for_date
    filter(lambda item: item["status"] != "UnAvailable", response.json()["slots"])
KeyError: 'slots'
$ 
```

Any ideas? - does the script still work?

**Comment by ButterflyBug** [comment]
Hi :) IThanks for info ;D It looks like Tesco has changed their internal API so the library needs to be updated ;) I'm working on it ;D
